name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # Allow manual triggers

env:
  PROJECT_NAME: brady-auto-scan-pdf

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Cloudflare Pages
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
        env:
          NODE_ENV: production

      - name: Create Cloudflare Pages project if not exists
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages project create ${{ env.PROJECT_NAME }} --production-branch=main
        continue-on-error: true  # Will fail if project already exists, that's OK

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy frontend/dist --project-name=${{ env.PROJECT_NAME }} --branch=${{ github.ref_name }}

      - name: Print Deployment URL
        run: echo "Deployed to Cloudflare Pages! 🚀"
